### ISSUE TITLE
Change package manager to Pipenv

### ISSUE THREAD

**Issue by RodrigoCMoraes** [RodrigoCMoraes/face_recognition#1]
Pipenv is human level package manager and I like it a lot. I tested it for some months and it is very good!

**Comment by tandelDipak** [comment]
Can I work on this?

**Comment by mrunderline** [comment]
Hello,
I've read README file, would you explain difference between `requirements.txt` and `requirements_linux.txt` file? and why you have more dependencies in `requirements_linux.txt` file?

**Comment by RodrigoCMoraes** [comment]
Hello @mrunderline ,

There are two requirements file because one it's just for Linux environment (based on debian) and the other it's just for windows 10. Because at time that I made this repo and tested the requirements file in both OS I have errors.

But today I use pipenv as my package manager and I think, if pipenv was used we can use just one requirement (Pipfile and Pipfile.lock).

**Comment by RodrigoCMoraes** [comment]
what is your OS @mrunderline ? If you can test on distro based on Debian, like Ubuntu I can test on Windows 10. And if this test is ok, we can use just one file for packages dependencies.

**Comment by mrunderline** [comment]
Good idea! Fortunately I'm using Ubuntu 19.04. And now i'm trying to install `requirements.txt` on my machine; if i gave an error, i'll report to you.

**Comment by RodrigoCMoraes** [comment]
Cool! I'll be waiting for testings.

**Comment by mrunderline** [comment]
At first I've create a virtualenv using pipenv and python 3.7, but `intel-numpy` library wasn't compatible with this version.
So I tried python 3.5 and now everything work fine! Just formatting strings and some package versions changed a little.
I would send you a PR soon...

**Comment by RodrigoCMoraes** [comment]
@mrunderline just pipenv unfortunately doesn't work for windows when I test, but I add more comments to PR that you request.

**Comment by RodrigoCMoraes** [comment]
Solved in [#pr15](https://github.com/RodrigoCMoraes/face_recognition/pull/15)
