### ISSUE TITLE
Make run in CPU

### ISSUE THREAD

**Issue by RodrigoCMoraes** [RodrigoCMoraes/face_recognition#3]
This repo was prepared to run just with GPU, but I think that running CPU with small images it won't take to long to run.

**Comment by gunjanraval** [comment]
How do you want to integrate this, like a completely different file name mtcnn_demo_CPU.py and the current be renamed to mtcnn_demo_GPU.py?

**Comment by RodrigoCMoraes** [comment]
Actually I didnt't think about that, but the way that you said are cool. I am glad if you can contribute with this.

**Comment by gunjanraval** [comment]
Yeah sure! I'll generate a PR
