### ISSUE TITLE
Improve documentation to bet new comers

### ISSUE THREAD

**Issue by RodrigoCMoraes** [RodrigoCMoraes/face_recognition#4]
Add GitHub recommended docs to help contribute with this repo!

**Comment by SHUBHAMGOGATE** [comment]
What Exactly do I have to add?

**Comment by RodrigoCMoraes** [comment]
Add a cool and inclusive Code of conduct and simple Contributing .md files will be good to go.

**Comment by dhrubo55** [comment]
Hey i have added a Contribution.md file with Code of conduct. Gave you a pull request. Please tell me what to modify and where if you need any. Thank you.

**Comment by RodrigoCMoraes** [comment]
Thanks @dhrubo55 !
